language:
    - java

jdk:
    - oraclejdk8
    - openjdk7

script:
    - mvn clean test
    - ls -lah

cache:
    directories:
        - $HOME/.m2   #Cache para dependencias

dist:
    - trusty

sudo:
    - false

notifications:
    - email: false  #Desactivamos notificaciones